@startuml
title Diagrama de Secuencia: Generar Ruta Tentativa (Interacción Microservicios)

hide footbox
autonumber

participant "TramosService" as TC
participant "EnviosService" as EC
participant "ContenedorService" as CC
participant "UsuarioService" as UC
participant "CamionesService" as CMC
participant "UbicacionesService" as UBC
participant "OSRM_API" as OSRM

TC -> TC: getRutaTentativa(RutaGetOpcionesRequest)
activate TC

' 1. Obtener Solicitud
TC -> EC: getSolicitudTrasladoById(idSolicitud)
activate EC
EC --> TC: SolicitudTraslado
deactivate EC

' 2. Obtener Contenedor (Cadena de llamadas)
TC -> CC: getById(idContenedor)
activate CC

    CC -> UC: getById(idCliente)
    activate UC
    UC --> CC: Usuario
    deactivate UC

CC --> TC: Contenedor
deactivate CC

' 3. Obtener Costos y Consumos de Camiones
TC -> CMC: getPromedioCostoBase(peso, volumen)
activate CMC
CMC --> TC: BigDecimal (Costo Promedio)
deactivate CMC

TC -> CMC: getConsumoPromedio()
activate CMC
CMC --> TC: BigDecimal (Consumo Promedio)
deactivate CMC

' 4. Loop de Ubicaciones y Cálculo de Rutas
group Procesamiento de Tramos (Loop Ubicaciones)
    
    loop Por cada par de ubicaciones (Origen -> Destino)
        
        ' Obtener Origen
        TC -> UBC: getUbicacionById(idOrigen)
        activate UBC
        UBC --> TC: Ubicacion (Origen)
        deactivate UBC

        ' Obtener Destino
        TC -> UBC: getUbicacionById(idDestino)
        activate UBC
        UBC --> TC: Ubicacion (Destino)
        deactivate UBC

        ' Calcular Distancia Externa (OSRM)
        TC -> OSRM: calcularDistancia(origen, destino)
        activate OSRM
        OSRM --> TC: RouteResponse (Distancia y Duración)
        deactivate OSRM

    end
end


TC -> EC: editSolicitud(SolicitudEditRequest)
activate EC
EC --> TC: SolicitudEditResponse
deactivate EC

TC --> TC: RutaGetOpcionesResponse
deactivate TC

@enduml
