@startuml
title Diagrama de Secuencia: Registro Solicitud (Reutilización de Contenedor)

hide footbox
autonumber

participant "SolicitudService" as SC
participant "ContenedorService" as CC

SC -> SC: register(SolicitudRegisterRequest)
activate SC

group Try: Buscar Contenedor Existente
    SC -> CC: getByPesoVolumen(peso, volumen)
    activate CC
    
    alt Contenedor encontrado y sin cliente
        CC --> SC: Contenedor
        SC -> CC: asignarCliente(idContenedor, idCliente)
        CC --> SC: ok
    else Contenedor ocupado o no existe
        CC --> SC: Error 404 (ServiceError)
        deactivate CC
    end
end

group Catch [404]: Crear Nuevo Contenedor
    
    SC -> CC: register(peso, volumen, idCliente)
    activate CC
    CC --> SC: idNuevoContenedor
    deactivate CC

    SC -> CC: getById(idNuevoContenedor)
    activate CC
    CC --> SC: Contenedor (Nuevo)
    deactivate CC
end

SC -> SC: save(Solicitud)

SC --> SC: SolicitudGetByIdResponse
deactivate SC

@enduml
