@startuml
title Diagrama de Secuencia: Registrar Inicio de Tramo

hide footbox
autonumber

participant "TramosService" as TC
participant "EnviosService" as EC
participant "CamionesService" as CMC
participant "ContenedorService" as CC

TC -> TC: registrarInicioTramo(TramoInicioTramoRequest)
activate TC

' 1. Validación de Solicitud
TC -> EC: getSolicitudTrasladoById(idSolicitud)
activate EC
EC --> TC: SolicitudTraslado
deactivate EC

' 2. Validación y Bloqueo de Camión
TC -> CMC: getById(dominio)
activate CMC
CMC --> TC: Camion
deactivate CMC


TC -> CMC: cambiarDisponibilidad(dominio, false)
activate CMC
CMC --> TC: ok
deactivate CMC

' 3. Gestión del Contenedor
TC -> CC: getById(idContenedor)
activate CC
CC --> TC: Contenedor
deactivate CC

alt Contenedor sale de Depósito
    TC -> CC: cambioDeEstado(idContenedor, EN_TRANSITO)
    activate CC
    CC --> TC: ok
    deactivate CC
end

' 4. Lógica del Primer Tramo
alt Es el Primer Tramo (Orden 1)

    TC -> EC: cambioDeEstadoSolicitud(idSolicitud, EN_TRANSITO)
    activate EC
    EC --> TC: ok
    deactivate EC

    TC -> CC: cambioDeEstado(idContenedor, EN_TRANSITO)
    activate CC
    CC --> TC: ok
    deactivate CC
end

TC --> TC: void (Exito)
deactivate TC

@enduml
